# file: .travis.yml
osx_image: xcode7.3
podfile: SPTestRailReporter/Podfile
rvm: 2.2.2

before_install:
  - gem install cocoapods
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

language: objective-c

script:./cleanbuildtest.sh
