# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TestRailReporter' do
end

target 'TestRailReporterTests' do
pod 'NSData+Base64', '~> 1.0'
pod 'AFNetworking', '2.5.4'
pod 'JSONModel'
end

