source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SPTestRailReporter' do
end

target 'SPTestRailReporterTests' do
pod 'NSData+Base64', '1.0.0'
pod 'AFNetworking', '2.5.4'
pod 'JSONModel', '1.2.0'
end